
SET SERVEROUTPUT ON;
DECLARE
  USER_NAME VARCHAR2(200);
BEGIN
  USER_NAME := 'admin';

  CREATE_PARENT_REGIONS(
    USER_NAME => USER_NAME
  );
END;

SELECT DISTINCT c.RGN_ID, c.CNTRY AS a, c.CNTY as b, c.CNSTTNCY as c, c.CRET_DATE FROM RCVR_RGN c WHERE c.CNTY IS NOT NULL AND c.CNSTTNCY IS NOT NULL AND c.WRD IS NULL;
SELECT DISTINCT c.RGN_ID, c.CNTRY AS a, c.CNTY as b, c.CNSTTNCY as c, c.CRET_DATE FROM RCVR_RGN c WHERE c.CNTY IS NOT NULL AND c.CNSTTNCY IS NULL;
SELECT DISTINCT c.RGN_ID, c.CNTRY AS a, c.CNTY as b, c.CNSTTNCY as c, c.CRET_DATE FROM RCVR_RGN c WHERE c.CNTY IS NULL AND c.CNSTTNCY IS NULL;

SELECT DISTINCT * FROM RCVR_RGN c WHERE c.CNTY IS NOT NULL AND c.CNSTTNCY IS NOT NULL AND c.WRD IS NULL;
SELECT DISTINCT * FROM RCVR_RGN c WHERE c.CNTY IS NOT NULL AND c.CNSTTNCY IS NULL;
SELECT DISTINCT * FROM RCVR_RGN c WHERE c.CNTY IS NULL AND c.CNSTTNCY IS NULL;

SELECT rr.RGN_ID FROM RCVR_RGN rr WHERE rr.CNTRY IN ( SELECT c.CNTRY_NAM FROM CNTRY c WHERE c.CNTRY_ID in (1) ) AND rr.CNTY IS NULL AND rr.CNSTTNCY IS NULL AND rr.WRD IS NULL;
SELECT rr.RGN_ID FROM RCVR_RGN rr WHERE rr.CNTY IN ( SELECT c.CNTY_NAM FROM CNTY c WHERE c.CNTY_ID in (39,40,41) ) AND rr.CNTY IS NOT NULL AND rr.CNSTTNCY IS NULL AND rr.WRD IS NULL;
SELECT rr.RGN_ID FROM RCVR_RGN rr WHERE rr.CNSTTNCY IN ( SELECT c.CNSTTNCY_NAM FROM CNSTTNCY c WHERE c.CNSTTNCY_ID in (127,128,129,130,131,132) ) AND rr.CNTY IS NOT NULL AND rr.CNSTTNCY IS NOT NULL AND rr.WRD IS NULL;